# justitemclear 插件配置文件

# 清理间隔设置（分钟）
cleanup-interval:
  items: 10    # 掉落物清理间隔（分钟）

# 清理设置
cleanup:
  enabled:
    items: true    # 是否清理掉落物


  world-whitelist:
    - ""    # 白名单世界，在此列表中的世界不会被清理

# 消息配置
# 声音配置
sounds:
  countdown: "BLOCK_NOTE_BLOCK_PLING"  # 倒计时提示音
  completion: "ENTITY_PLAYER_LEVELUP"  # 清理完成提示音

# 消息配置
messages:
  # 是否显示前缀
  show_prefix: true
  # 前缀文本
  prefix: "&r[&b服务器娘&r] "
  item_type: "掉落物"  # 不建议修改
  # 提示显示方式开关
  display:
    chat: true
    actionbar: true
    bossbar: true
  help:
    title: "&6=== JustItemClear 帮助 ==="
    commands:
      - "/jic help: 显示帮助信息"
      - "/jic reload: 重载配置文件"
      - "/jic clear: 立即清理物品"
      -
  
  log:
    world_cleanup: "世界 '%s' 清理了 %d 个%s"
    total_cleanup: "&a总共清理了 &r%d &a个%s"

  player:
    cleanup_completed: "&a清理完成!"
    command_no_permission: "你没有权限执行此命令！"
    command_reloaded: "justitemclear 配置已重载！"
    quick_clean_start: "立即清理已启动！"
    no_permission: "你没有权限执行此命令！"

  countdown:
    custom_minutes: "&e距离下次清理还有 &r%d &e分钟"
    five_minutes: "&e还有 &r5分钟 &e清理%s"
    one_minute: "&e还有 &r1分钟 &e清理%s"
    thirty_seconds: "&e还有 &r30秒 &e清理%s"
    fifteen_seconds: "&e还有 &r15秒 &e清理%s"
    seconds: "&c还有 &r%d秒 &c清理%s"
    second_warning: "秒后清理所有%s"
    completed: "&a已清理 &e%d 个&a%s!"
    log:
      cleanup_counter: "%s清理次数: %d/%d"