name: JustItemClear
main: com.example.justitemclear.justitemclear
version: 1.0
api-version: '1.16'
author: SnowYU_
description: 服务器实体掉落物清理插件
website: https://example.com

commands:
    justitemclear:
      description: justitemclear插件的主命令
      usage: /<command> help
      aliases: [jic]

permissions:
    justitemclear.admin:
      description: 允许使用justitemclear的所有管理命令
      default: op
    justitemclear.reload:
      description: 允许重载配置文件
      default: op
      children:
        justitemclear.admin: true
    justitemclear.clear:
      description: 允许立即清理
      default: op
      children:
        justitemclear.admin: true